spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/jwtdb
    username: jwtuser
    password: jwtpass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/jwtdb
    user: jwtuser
    password: jwtpass
    locations: classpath:db/migration
    baselineOnMigrate:  true

      
app:
  security:
    jwt:
      secret-key: 435832564363664276414e566c786478386473444c694245496466553871684d
      access:
        exp: 600 # 10 min
      refresh:
        exp: 1209600 # 14 days
      reset:
        exp: 600 # 10 min

# 435832564363664276414e566c786478386473444c694245496466553871684d


